name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Install Aiken
        run: cargo install --git https://github.com/aiken-lang/aiken.git

      - name: Run Aiken check on
        working-directory: ./contracts
        run: aiken check
        shell: bash
